language: node_js

node_js:
  - "lts/dubnium"

install:
  - npm ci

script:
  - npm run lint

before_deploy:
  - git config user.name "${GITHUB_NAME}"
  - git config user.email "${GITHUB_EMAIL}"
  - npm run build

deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master
    tags: true